/api/*  https://bug-tracker-api-n59y.onrender.com/api/:splat  200

/*      /index.html    200

[[redirects]]
  from = "/api/*"
  to = "https://frontend-take-home-service.fetch.com/:slug"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200